Convert HEIC to JPG on upload for darwin
keybase/client pull request #26325
Opened 2024-03-11 19:48 UTC by joshblum

Convert from HEIC to JPEG during the preprocess pass

@chrisnojima @mmaxim

2024-03-12 19:49 UTC, joshblum commented
New setting, shows on darwin devices

![paste (3)](https://github.com/keybase/client/assets/1144020/f25545f4-b018-4d4a-9911-a9ff0d0f0c43)

2024-03-14 14:15 UTC, mmaxim requested changes

2024-03-14 14:15 UTC, mmaxim commented on go/chat/attachments/preview_darwin.go
> +void HEICToJPEG(const char* inFilename) {
Should probably do better error handling here. Can you some global variable like we do for the result to make it easier to interface with Go.

2024-03-14 14:16 UTC, mmaxim commented on go/chat/attachments/preview_darwin.go
> +void HEICToJPEG(const char* inFilename) {
That is, if this function fails, we just send the HEIC image as a file, but not sending a blank attachment or whatever would happen.

2024-03-14 17:23 UTC, mmaxim approved these changes

2024-03-14 17:34 UTC, merged